### ISSUE TITLE
Error in training with multi GPUs

### ISSUE THREAD

**Issue by jianglongye** [walsvid/Generation3D#2]
Thanks for your excellent work!

I followed the instructions in the README and successfully trained the disn model on a single GPU. However, when I extended to multiple GPUs, I encountered the following error.

```
=> creating /root/Generation3D/experiments/logs/disn
=> creating /root/Generation3D/experiments/checkpoints/disn/disn_default_1122151835
=> creating /root/Generation3D/experiments/summary/disn/disn_default_1122151835
=> creating summary writer
datasets/data/shapenet/SDF_v1
datasets/data/shapenet/ShapeNetRenderingh5_v1
Traceback (most recent call last):
  File "train.py", line 41, in <module>
    main()
  File "train.py", line 37, in main
    trainer.train()
  File "/root/Generation3D/scheduler/base/base_trainer.py", line 139, in train
    out = self.train_step(batch)
  File "/root/Generation3D/scheduler/base/base_trainer.py", line 106, in train_step
    loss, loss_summary = self.criterion(out, input_batch)
  File "/opt/conda/envs/gen3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/Generation3D/utils/parallel.py", line 132, in forward
    outputs = _criterion_parallel_apply(replicas, inputs, targets, kwargs)
  File "/root/Generation3D/utils/parallel.py", line 201, in _criterion_parallel_apply
    raise output
  File "/root/Generation3D/utils/parallel.py", line 176, in _worker
    output = module(input, *target, **kwargs)
  File "/opt/conda/envs/gen3d/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/Generation3D/models/losses/sdf_loss.py", line 16, in forward
    outputs = pred_dict["pred_sdf"]
TypeError: list indices must be integers or slices, not str
```

Here is my running command:

```
CUDA_VISIBLE_DEVICES=0,1,2,3 python train.py --options configs/disn/default.yml --batch-size 16
```

I have tried to debug and it seems to be a problem with the `DataParallelCriterion`, but I failed to figure it out. Besides, I didn't modify any code.

**Comment by walsvid** [comment]
This may be related to the network output is a dictionary, and there may be some bugs in the implementation of multi-GPU. I will update it as soon as possible. Please wait for a moment. Before that, maybe you can directly use `Dataparallel`, though may load imbalance, but should get the loss without bug.

**Comment by jianglongye** [comment]
Thanks, `Dataparallel` does work on multi GPUs.
