### ISSUE TITLE
Where is img_ori come from 

### ISSUE THREAD

**Issue by xiyuanssxx** [walsvid/Generation3D#6]

**Comment by ghost** [comment]
Traceback (most recent call last):
  File "/root/Desktop/222Generation3D-master/train.py", line 41, in <module>
    main()
  File "/root/Desktop/222Generation3D-master/train.py", line 37, in main
    trainer.train()
  File "/root/Desktop/222Generation3D-master/scheduler/base/base_trainer.py", line 135, in train
    for step, batch in enumerate(train_data_loader):
  File "/root/.conda/envs/gen3d/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 346, in __next__
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/root/.conda/envs/gen3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/.conda/envs/gen3d/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/root/Desktop/222Generation3D-master/datasets/p2m_shapenet.py", line 60, in __getitem__
    img_ori, pt, nm = self.get_img(img_dir, num)
  File "/root/Desktop/222Generation3D-master/datasets/p2m_shapenet.py", line 40, in get_img
    with h5py.File(img_h5, 'r') as h5_f:
  File "/root/.conda/envs/gen3d/lib/python3.6/site-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/root/.conda/envs/gen3d/lib/python3.6/site-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = 'datasets/data/shapenet/ShapeNetRenderingh5_v1/02691156/d3580448933d00fd90b1d6deb98feec6/17_sr.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)
